# Generated by Django 4.1.2 on 2022-10-31 21:00

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('main_app', '0003_rename_projects_project'),
    ]

    operations = [
        migrations.RenameField(
            model_name='project',
            old_name='tools',
            new_name='tool',
        ),
    ]
